### PR TITLE
Make MailerInterface lightweight

### LINKED ISSUE #93: [BC break] Simplify the MailerInterface
> @Stampie/collaborators this discussion is about a BC breaking change, so a decision has to be taken before releasing the 1.0 version. If no decision is taken, the release itself will force the decision to be `no` (at least until 2.0).

The current MailerInterface looks like this: https://github.com/Stampie/Stampie/blob/293be7036b977be7fbb15e2fcf2140255de2b0c7/lib/MailerInterface.php#L12-L35

I suggest to simplify it to this:

```php
interface MailerInterface
{
    /**
     * @param MessageInterface $message
     *
     * @throws Exception on failure
     */
    public function send(MessageInterface $message): void;
}
```

Here are my reasoning for the different changes:

- forcing the usage of a server token makes it harder to implement things. Each adapter has a different meaning for it (being an API key, a username+password, etc...), meaning that using the getter and setter requires checking the implementation being used anyway (and so the fact that the methods are in the interface is useless). I think the authentication should be an implementation detail of the Mailer: each mailer would be free to take one or multiple parameters for the auth (allowing to split the username and password for instance, which might make it easier to use env variables for instance), and also to decide whether the auth credentials should be mutable and exposed to consuming code (IMO, they should not)
- the fact that the mailer uses a HTTPlug client should be an implementation detail as well (for instance, in Stampie extra, it does not use a HTTP client, but another Stampie mailer, for which it can fortunately forward the setter, but this is weird), and I see no reason to make it mutable either (so it should be a constructor argument)
- instantiating a new mailer currently creates a broken object (as mandatory dependencies are not passed in the constructor)
- the configuration API of mailers is already wider than the MailerInterface (they all have a `setMessageFactory` setter for instance)
- returning a boolean from `send` makes debugging harder because you don't have an explanation on failure. And in practice, our own implementations are already all throwing exceptions on failures instead of returning true. So our signature is already `@return true  @throws ApiException @throws HttpException` in practice. Returning `true` and never `false` looks weird. Even if we reject the change from `@return true` to `@return void` (with or without return type depending on PHP support), we should at least update the interface to document our actual contract.

what do you think @Stampie/collaborators ?

### PR DESCRIPTION
**Pull request by fbourigault**
This remove the `setHttpClient`, `setServerToken` and `getServerToken` from `MailerInterface`.

The `MailerInterface` contract is now only about sending messages without exposing implementation details to clients.

Also the `MailerInterface::send` method no longer returns a boolean. If no
exception is thrown, then the message was successfully sent.

Close #93.

## Todo

- [x] Update mailers to not return a boolean.
- [x] Introduce our own exception interface.
- [x] Add changelog entries.

### CODE REVIEW

File: lib/MailerInterface.php [hunk 1]
```diff
@@ -2,34 +2,14 @@
...
-     */
-    public function getServerToken();
-
-    /**
+     * Sends an email message.
+     *
      * @param MessageInterface $message
      *
-     * @return bool
+     * @throws \Exception if an error happens during sending the message.
```
Comment (fbourigault) [inline lib/MailerInterface.php]: Should we use `\Exception` here or introduce our exception interface? I'm asking this because Httplug has his own exception and this interface looks like `Http\Client\HttpClient` to me.

Comment (stof) [reply lib/MailerInterface.php]: We always throw our own exceptions (ApiException and HttpException) for clean failures of the API (and these are cases that you may want to catch)

Comment (stof) [reply lib/MailerInterface.php]: We may want to add an interface implemented by both classes though, for easier catching

**Comment by fbourigault** [comment]
I introduced the `Stampie\ExceptionInterface` and make all our exceptions implement it.

I would also start a discussion about the exceptions. What about having two base exceptions like MessageException when the message is malformed and TransportException when the mailer was unable to send  the message at all?

File: lib/MailerInterface.php [hunk 2]
```diff
@@ -2,34 +2,14 @@
...
-     * @return string
-     */
-    public function getServerToken();
-
-    /**
+     * Sends an email message.
+     *
      * @param MessageInterface $message
      *
-     * @return bool
```
Comment (stof) [inline lib/MailerInterface.php]: you should remove the `true` return value from implementations

**Comment by stof** [comment]
MalformedMessageException looks better than just MessageException then

**Comment by stof** [comment]
btw, I see no place currently which could use it, so not sure it is worth it.

**Comment by fbourigault** [comment]
Btw, as the interface say that `Stampie\ExceptionInterface` are thrown, we can do what ever we want in minor releases.

**Comment by stof** [comment]
@fbourigault any chance to finish this ? I see only 3 remaining tasks for the 1.0.0 milestone:

- finishing this interface change (and updating `stampie/extra` to reflect it)
- finishing the upgrade of the bundle
- finishing the Sendgrid v3 migration (as the change in the auth credentials is a BC break)

Anything else (Sparkpost and Mailjet support, cleaning of auth configuration APIs for each mailer, etc...) can be done in minor versions.

**Comment by fbourigault** [comment]
I will try to finish this one tonight, the other one later this week.

**Comment by fbourigault** [comment]
This is now ready!

**Comment by fbourigault** [comment]
@stof is this ok yo you?

File: Changelog.md [hunk 3]
```diff
@@ -4,6 +4,8 @@ The change log describes what been "Added", "Removed", "Changed" or "Fixed" betw
 
 ### Unreleased
 
+- The `setHttpClient`, `setServerToken` and `getServerToken` methods have been removed from `Stampie\MailerInterface`.
+- The `Stampie\MailerInterface::send` method no longer return a boolean. Errors are now reported using exceptions that implements `Stampie\ExceptionInterface`.
```
Comment (stof) [inline Changelog.md]: I would add a note explaining that core implementations were already throwing exception here (to explain that our BC break here is minimal)

**Comment by fbourigault** [comment]
I've added the note to explain that the `MailerInterface::send` BC break is minimal.

There is nothing to do for the `handle` methods.

**Comment by fbourigault** [comment]
I'm merging this to move forward. @stof if you have some more requests, tell me and I will open a new PR.

Thank you for review!
